DATA_PATH = "../../dataset/split_prepped_data"
RESULT_PATH = "./training_result"
ADDITIONAL_DATA_PATH = "../../dataset/prepped_additional_data"
ADDITIONAL_DATA__2_PATH = "../../dataset/split_prepped_additional_data_2"
BASE_PATH = "../../dataset"